### ISSUE TITLE
Problems with 3D genome structural model from Chrom3D

### ISSUE THREAD

**Issue by QianzhaoJ** [Chrom3D/Chrom3D#11]
Hi :
I have got 3D genome structural model using Chrom3D, and used Chimera to visualize the 3D genome model just like describing in Nat protocal . But I found two questions that made me feel confused. 
1.Many beads are not placed within 5 µm nucleus;
2.Most beads stay together, but some beads that stay together are far away from most beads . Is that normal?
I typed ` Chrom3D -y 0.15 -r 5.0 -n 2000000 -o inter_intra_chr.diploid.cmm inter_intra_chr.diploid.gtrack`
and This is the full output message

> #Rescaled bead sizes from 38.704 to 0.15
> #chromosomes: 46
> #beads: 4838
> #interactions: 3266
> #interactions with given weight: 0
> #non-bounded interactions with given distance: 0
> #upper-bounded interactions with given distance: 0
> #lower-bounded interactions with given distance: 0
> #periphery beads: 0
> #periphery beads (with weights): 0
> #center beads: 0
> #center beads (with weights): 0

Last , I want to study interchromosomal pairwise distance using Chrom3D ,Can you give me some suggestions?

Best wishes
Qianzhao

**Comment by jonnings** [comment]
Hi, QianzhaoJ.
Since you are not using constraints towards the nuclear periphery, you need to specify that the beads should be constrained inside the nucleus. This is done by adding the --nucleus switch:
```
   --nucleus
     Add constraints such that all beads are pushed towards the inside of
     the nucleus
```
So, this will be the right set of parameters:
`Chrom3D --nucleus -y 0.15 -r 5.0 -n 2000000 -o inter_intra_chr.diploid.cmm inter_intra_chr.diploid.gtrack`

You can add interchromosomal interactions in the same way as you add intrachromosomal contacts in the GTrack files. You should check out the [example pipeline](https://github.com/Chrom3D/pipeline) if you are uncertain about how to do this. Pairwise distances can be extracted in the output CMM file. This file contains x,y,z coordinates for each bead in the final model. Since the CMM file is using a simple XML format, it should be easy to read it into R, Python etc.

**Comment by QianzhaoJ** [comment]
It works! Thank you for your help!

I have added interchromosomal interactions，and got CMM file . Can I find the change of interchromosomal distance directly (farther or closer) by visualization (like Chimera) ?

I tried ,but the answer seems to be no .

发件人: jonnings<mailto:notifications@github.com>
发送时间: 2018年10月17日 15:34
主题: Re: [Chrom3D/Chrom3D] Problems with 3D genome structural model from Chrom3D (#11)


Hi, QianzhaoJ.
Since you are not using constraints towards the nuclear periphery, you need to specify that the beads should be constrained inside the nucleus. This is done by adding the --nucleus switch:

   --nucleus

     Add constraints such that all beads are pushed towards the inside of

     the nucleus

So, this will be the right set of parameters:
Chrom3D --nucleus -y 0.15 -r 5.0 -n 2000000 -o inter_intra_chr.diploid.cmm inter_intra_chr.diploid.gtrack

You can add interchromosomal interactions in the same way as you add intrachromosomal contacts in the GTrack files. You should check out the example pipeline<https://github.com/Chrom3D/pipeline> if you are uncertain about how to do this. Pairwise distances can be extracted in the output CMM file. This file contains x,y,z coordinates for each bead in the final model. Since the CMM file is using a simple XML format, it should be easy to read it into R, Python etc.

―

**Comment by jonnings** [comment]
Good that it now works. You can extract distances by computing them from the CMM file using for example Python or R. Chimera is mainly a structure visualization tool.
